[package]
name = "rustlings"
version = "4.6.0"
authors = ["anastasie <ana@ana.st>", "Carol (Nichols || Goulding) <carol.nichols@gmail.com>"]
edition = "2021"

[dependencies]
argh = "0.1.12"
indicatif = "0.17.7"
console = "0.15.7"
notify = "4.0.17"
toml = "0.8.2"
regex = "1.10.1"
serde = {version = "1.0.189", features = ["derive"]}

[[bin]]
name = "rustlings"
path = "src/main.rs"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
glob = "0.3.1"
