[package]
name = "rustlings"
version = "4.6.0"
authors = ["anastasie <ana@ana.st>", "Carol (Nichols || Goulding) <carol.nichols@gmail.com>"]
edition = "2021"

[dependencies]
argh = "0.1.10"
indicatif = "0.17.3"
console = "0.15.5"
notify = "4.0.17"
toml = "0.7.2"
regex = "1.7.1"
serde = {version = "1.0.152", features = ["derive"]}

[[bin]]
name = "rustlings"
path = "src/main.rs"

[dev-dependencies]
assert_cmd = "2.0.8"
predicates = "2.1.5"
glob = "0.3.1"
