[package]
name = "rustlings"
version = "4.6.0"
authors = ["anastasie <ana@ana.st>", "Carol (Nichols || Goulding) <carol.nichols@gmail.com>"]
edition = "2021"

[dependencies]
argh = "0.1.8"
indicatif = "0.16.2"
console = "0.15.0"
notify = "4.0.17"
toml = "0.5.9"
regex = "1.6.0"
serde = {version = "1.0.140", features = ["derive"]}

[[bin]]
name = "rustlings"
path = "src/main.rs"

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"
glob = "0.3.0"
