[book]
authors = ["sabertazimi"]
language = "zh-CN"
multilingual = false
src = "docs"
title = "awesome-rust"

[output.html]
git-repository-url = "https://github.com/sabertazimi/awesome-rust"
edit-url-template = "https://github.com/sabertazimi/awesome-rust/edit/main/{path}"

[output.html.playground]
editable = true
copy-js = true
line-numbers = true

[output.html.fold]
enable = true
level = 1

[rust]
edition = "2021"
