[book]
title = "awesome-rust"
authors = ["sabertazimi"]
description = "Rust prototypes."
src = "docs"
language = "zh-CN"
multilingual = false

[output.html]
git-repository-url = "https://github.com/sabertazimi/awesome-rust"
edit-url-template = "https://github.com/sabertazimi/awesome-rust/edit/main/{path}"
site-url = "/awesome-rust/"

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = true

[output.html.fold]
enable = true
level = 1

[rust]
edition = "2021"
