[package]
name = "basis"
version = "0.1.0"
edition = "2021"
description = "Rust Basis"
license = "MIT"
homepage = "https://github.com/sabertazimi/awesome-rust"
repository = "https://github.com/sabertazimi/awesome-rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
